Selenium turbal
RV2022ATQC/CrashCourseAT2022 pull request #192
Opened 2022-05-22 21:10 UTC by TurbalY

2022-05-23 07:16 UTC, romanukhaav requested changes

2022-05-23 07:16 UTC, romanukhaav commented on Projects/TEAM-1/Turbal Y/Selenium_1/Selenium_1/Selenium_1/Program.cs
> +        {
We no need an empty Main method. We should just change the Output type of the project to ClassLibrary

<img width="808" alt="image" src="https://user-images.githubusercontent.com/15199521/169763879-0099ff93-e0f8-41c1-b821-26f7deb19518.png">

2022-05-23 07:16 UTC, romanukhaav commented on Projects/TEAM-1/Turbal Y/Selenium_1/Selenium_1/Selenium_1/SeleniumFirst.cs
> +            driver.Quit();
We should have some assertions in the test.

2022-05-23 07:16 UTC, romanukhaav commented on Projects/TEAM-1/Turbal Y/Selenium_1/Selenium_1/Selenium_1/SeleniumFirst.cs
> +
Could you please perform some cleanup and remove all commented code?

2022-05-23 08:44 UTC, TurbalY commented
Thanks a lot. I have some problem dealing with selenium driver. Local host
stop connection after 60 seconds. I 'm solving this problem .


пн, 23 трав. 2022, 10:16 користувач Anton ***@***.***> пише:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Projects/TEAM-1/Turbal Y/Selenium_1/Selenium_1/Selenium_1/Program.cs
> <https://github.com/RV2022ATQC/CrashCourseAT2022/pull/192#discussion_r879095274>
> :
>
> > @@ -0,0 +1,15 @@
>
> +﻿using System;
>
> +using System.Collections.Generic;
>
> +using System.Linq;
>
> +using System.Text;
>
> +using System.Threading.Tasks;
>
> +
>
> +namespace Selenium_1
>
> +{
>
> +    class Program
>
> +    {
>
> +        static void Main(string[] args)
>
> +        {
>
>
> We no need an empty Main method. We should just change the Output type of
> the project to ClassLibrary
>
> [image: image]
> <https://user-images.githubusercontent.com/15199521/169763879-0099ff93-e0f8-41c1-b821-26f7deb19518.png>
> ------------------------------
>
> In Projects/TEAM-1/Turbal
> Y/Selenium_1/Selenium_1/Selenium_1/SeleniumFirst.cs
> <https://github.com/RV2022ATQC/CrashCourseAT2022/pull/192#discussion_r879096029>
> :
>
> > +             ChromeOptions options = new ChromeOptions();
>
> +           // options.AddArguments("--start-maximized");
>
> +           //  options.AddArguments("--disable-web-security");
>
> +            IWebDriver driver = new ChromeDriver();
>
> +            //IWebDriver driver = new FirefoxDriver();
>
> +            driver.Navigate().GoToUrl("http://demo.guru99.com/test/guru99home");
>
> +           // driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(10);
>
> +           // driver.FindElement(By.CssSelector("#search > input")).Clear();
>
> +           // driver.FindElement(By.CssSelector("#search > input")).SendKeys("Nokia" + Keys.Enter);
>
> +            // driver.FindElement(By.CssSelector("#search > My Account"));
>
> +            //driver.FindElement(By.CssSelector("#search > login")).SendKeys(Keys.Enter);
>
> +            // driver.FindElement(By.CssSelector("#search > E-Mail Address")).SendKeys("marianta1");
>
> +            // driver.FindElement(By.CssSelector("#search > Password")).SendKeys("marianta1" + Keys.Enter);
>
> +           // driver.FindElement(By.CssSelector("#search > input")).Clear();
>
> +           // driver.FindElement(By.CssSelector("#search > input")).SendKeys("iPhone" + Keys.Enter);
>
> +            driver.Quit();
>
>
> We should have some assertions in the test.
> ------------------------------
>
> In Projects/TEAM-1/Turbal
> Y/Selenium_1/Selenium_1/Selenium_1/SeleniumFirst.cs
> <https://github.com/RV2022ATQC/CrashCourseAT2022/pull/192#discussion_r879097154>
> :
>
> > +                [Test]
>
> +                public void selectDemo()
>
> +
>
> +                {
>
> +                    IWebDriver m_driver = new ChromeDriver("C:\\Users\\Юрий\\Documents\\GitHub\\CrashCourseAT2022\\Projects\\TEAM-1\\Turbal Y\\Selenium_1\\Selenium_1\\Selenium_1\\bin\\Debug");
>
> +                    m_driver.Url = "http://demo.guru99.com/test/guru99home/";
>
> +                    m_driver.Manage().Window.Maximize();
>
> +
>
> +                    IWebElement course = ***@***.***='awf_field-91977689']"));
>
> +
>
> +                    var selectTest = new SelectElement(course);
>
> +                    // Select a value from the dropdown				
>
> +                    selectTest.SelectByValue("sap-abap");
>
> +                    m_driver.Quit();
>
> +
>
> +
>
>
> Could you please perform some cleanup and remove all commented code?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/RV2022ATQC/CrashCourseAT2022/pull/192#pullrequestreview-981239157>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYTYBFJDZEYHJXFFKS6MEGLVLMWF3ANCNFSM5WT52BTQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-23 12:47 UTC, romanukhaav commented
> 
did you use the last selenium examples? I've already fixed this issue "Local host
stop connection after 60 seconds"

2022-05-25 20:54 UTC, romanukhaav approved these changes
It is better, but I still can't find Assertions in these tests

2022-05-25 21:36 UTC, romanukhaav approved these changes

2022-05-25 21:36 UTC, merged